name: Run Signoffs

on:
  workflow_dispatch:

jobs:
  run-signoffs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run signoffs script
        run: bash signoffs.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
