name: Run Signoffs

on:
  workflow_dispatch:

jobs:
  run-signoffs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run signoffs script
        run: |
          while read -r line; do
            IFS=',' read -ra names <<< "$line"
            issue_url=$(gh issue create --title "QA Signoff for: ${names[1]}" --body "$(cat ./issue.md)" --repo "${names[0]}")
            echo "$issue_url" >> issue_urls.txt
          done < ./repos.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}